---
title: "Data Import Script"
format: html
---

```{r packages}
install.packages("rmapshaper")
library(rmapshaper)
install.packages("jsonlite")
library(jsonlite)
library(tidyverse)
library(sf)

```

```{r}
towns <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/townssurvey_shp/TOWNSSURVEY_POLY.shp")

```

```{r}
towns |>
  filter(TOWN == "BOSTON") |>
  ggplot() +
  geom_sf()
```

```{r}
boston <- towns |>
  filter(TOWN == "BOSTON")
```

```{r}
ro618_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R06C18/LCLU_R06C18.shp")

ro619_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R06C19/LCLU_R06C19.shp")

ro620_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R06C20/LCLU_R06C20.shp")

ro718_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R07C18/LCLU_R07C18.shp")

ro719_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R07C19/LCLU_R07C19.shp")

ro720_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R07C20/LCLU_R07C20.shp")

ro818_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R08C18/LCLU_R08C18.shp")

ro819_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R08C19/LCLU_R08C19.shp")

ro820_tile <- st_read("/Users/isaiahd12/Documents/dsc210_welfare_proj/Environmental_welfare_proj_boston/data/imported_data/LCLU_R08C20/LCLU_R08C20.shp")
```

```{r}
st_crs(boston)
st_crs(ro618_tile)
```

```{r}
boston_crs <- st_crs(boston)

ro618_tile <- st_transform(ro618_tile, boston_crs)
ro619_tile <- st_transform(ro619_tile, boston_crs)
ro620_tile <- st_transform(ro620_tile, boston_crs)
ro718_tile <- st_transform(ro718_tile, boston_crs)
ro719_tile <- st_transform(ro719_tile, boston_crs)
ro720_tile <- st_transform(ro720_tile, boston_crs)
ro818_tile <- st_transform(ro818_tile, boston_crs)
ro819_tile <- st_transform(ro819_tile, boston_crs)
ro820_tile <- st_transform(ro820_tile, boston_crs)
```

```{r}
landcover_all <- bind_rows(
  ro618_tile, ro619_tile, ro620_tile,
  ro718_tile, ro719_tile, ro720_tile,
  ro818_tile, ro819_tile, ro820_tile
)

```

```{r}
#Validating geometry and landcover
landcover_all <- st_make_valid(landcover_all)

```

```{r}
boston_landcover <- st_intersection(boston, landcover_all)
```

```{r}
#convex hull of boston using st
boston_hull <- st_convex_hull(st_union(boston))
```

```{r}
#This filters 'landcover_all' to only keep rows that touch/overlap the 'boston_hull' Recommended
# sam mason, trying it for first time, taken from the web.. Hull rdoc.org is where 
#hull info is from
landcover_subset <- st_filter(landcover_all, boston_hull, .predicate = st_intersects)
```

```{r}
#final intersection
boston_landcover_final <- st_intersection(landcover_subset, boston)
```

```{r}
boston_landcover_final <- st_intersection(landcover_subset, boston) %>%
  #  Make geomes valid 
  st_make_valid() %>%
  # Extracing only the polygons/multipolygons from the collections
  st_collection_extract("POLYGON") %>%
  # Drop empty geomes to prep for final spacial join later on.
  filter(!st_is_empty(geometry))
```

## Import of WEB API facilites by the MBTA.


```{r}
# 1. Get the key from your environment
```

```{r}


my_actual_key <- "7e0be112692c4d56bfb4c8833de0a099"


api_url <- paste0("https://api-v3.mbta.com/facilities?include=stop&api_key=", my_actual_key)

# data import
raw_data <- fromJSON(api_url, flatten = TRUE)

# 4. make sure I got my data and debug
print(paste("Downloaded", nrow(raw_data$data), "rows of facilities data."))
```


##MBTA facitlies query api code


```{r}
head(facilities_boston_only$short_name, 10)

head(stations_clean$Station, 10)
```
```{r}


Target the ACTUAL Subway station table (usually Table 3 or 4)
url <- "https://en.wikipedia.org/wiki/List_of_MBTA_subway_stations"
page <- read_html(url)
all_tables <- page %>% html_table(fill = TRUE)

#  table that has "Station" and "City/neighborhood"

stations_scraped <- all_tables[[3]] # Trying table 3


facilities_ready <- facilities_boston_only %>%
  mutate(

    id_clean = str_remove(id, "BW-"), 
    id_clean = str_remove(id_clean, "place-")
  )

# 3. Create a manual 'Accessibility' flag based on your Platform Data
# Since your API data literally says "Mini-high platform", 
# THAT IS the accessibility info! 'Mini-high' means it IS ADA accessible.
# READ IF NEEDED, I was experiencing errors earlier with making this accessible read back to above 
#three lines for the purpose of this..... Might forget
facilities_final <- facilities_ready %>%
  mutate(
    Accessibility_Status = ifelse(str_detect(short_name, "Mini-high"), "Accessible", "Check Station")
  )

head(facilities_final$Accessibility_Status)
```

```{r}
# Finalizies and cleans up my facilities data
facilities_final_output <- facilities_final |>
  mutate(
    # Clean up the names for the final map labels
    clean_label = str_remove(short_name, "Mini-high platform "),
    # Geom being handled for my csv export
    lon = st_coordinates(geometry)[,1],
    lat = st_coordinates(geometry)[,2]
  )

# Wellness data for kaggle
write.csv(st_drop_geometry(facilities_final_output), 
          "../output/mbta_elevated_accessibility_wellness.csv", 
          row.names = FALSE)
```


```{r}
# Opening direct file to view my png
png("../output/final_wellness_map.png", width = 2400, height = 1800, res = 300)

#  Plot code to make it look pretty
ggplot() +
  geom_sf(data = boston_landcover_simple, aes(fill = COVERNAME), color = NA, alpha = 0.5) +
  geom_sf(data = facilities_final_output, aes(color = Accessibility_Status), size = 3) +
  scale_color_manual(values = c("Accessible" = "#0072B2", "Check Station" = "#D55E00")) +
  theme_minimal() +
  labs(title = "Elevated Transit Wellness: Boston",
       subtitle = "Mapping ADA 'Mini-High' Infrastructure across Land Cover",
       fill = "Land Type", color = "Status")

# Basically bypass my error from earlier.
dev.off()
```

